---
- name: Install Jenkins on Ubuntu EC2
  hosts: jenkins
  gather_facts: false
  become: true

  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600


    - name: Install dependencies for apt-transport-https, ca-certificates, curl, and gnupg
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg 
        state: present
        update_cache: yes

    - name: Create keyrings directory for Jenkins
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Download Jenkins GPG key
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /etc/apt/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Add Jenkins APT repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        filename: jenkins
        state: present


    - name: Update apt cache again after adding new repository
      apt:
        update_cache: yes


    - name: Install Java (OpenJDK 11 is recommended for Jenkins LTS) fontconfig
      apt:
        name: 
          - openjdk-21-jre
          - fontconfig
        state: present

    - name: Install Jenkins package
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins service is running and enabled at boot
      systemd:
        name: jenkins
        state: started
        enabled: yes


    - name: Wait for Jenkins to start (port 8080)
      wait_for:
        port: 8080
        timeout: 60
        state: started

    - name: Show Jenkins initial admin password
      slurp:
        src: /var/lib/jenkins/secrets/initialAdminPassword
      register: admin_password_raw

    - name: Print Jenkins initial admin password
      debug:
        msg: "Initial Jenkins password: {{ admin_password_raw['content'] | b64decode }}"

    - name: write password
      delegate_to: localhost
      become: false
      copy:
        dest: ./password
        content: "{{ admin_password_raw['content'] | b64decode }}"
