---
- name: Configure and Install Nginx on Ubuntu EC2
  hosts: nginx 
  gather_facts: false
  become: true

  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600 

    - name: Install Nginx package
      apt:
        name: nginx
        state: present


    - name: Deploy Nginx reverse proxy config for Jenkins
      copy:
        content: |
          server {
            listen 80;
            server_name {{ nginx_ip }};

            location / {
              proxy_pass http://{{ jenkins_ip }}:8080/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;

              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
            }
          }

        dest: /etc/nginx/conf.d/jenkins.conf
        mode: '0644'
        owner: root
        group: root
  
    - name: Reload Nginx to apply new config
      systemd:
        name: nginx
        state: restarted
        enabled: yes
