---
- name: Configure Salve Machine on Ubuntu EC2
  hosts: slave
  gather_facts: false
  become: true

  tasks:
    - name: Ensure apt cache is updated
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install dependencies 
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg 
          - openjdk-21-jre
          - fontconfig
        state: present

    - name: Change ownership of /home/ubuntu/jenkins
      file:
        path: /home/ubuntu/jenkins
        state: directory
        owner: ubuntu
        group: ubuntu
        recurse: yes    

